spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configserver
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10
